apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/repository-access: read-only
    kpt.dev/repository-content: external-blueprints
  name: nephio-example-packages
  namespace: default
spec:
  content: Package
  description: Nephio Example Packages
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-project/nephio-example-packages.git
  type: git
