apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/deployment-environment: production
  name: nephio-management
  namespace: default
spec:
  content: Package
  deployment: true
  description: Nephio Management Cluster Deployments
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-test/jbelamaric-demo-nephio-management.git
    secretRef:
      name: nephio-test-auth
  type: git
