apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/repository-content: organizational-blueprints
  name: org-catalog
  namespace: default
spec:
  content: Package
  description: Organizational Catalog
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-test/jbelamaric-demo-org-catalog.git
    secretRef:
      name: nephio-test-auth
  type: git
