apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  name: team-catalog-hr-apps
  namespace: default
spec:
  content: Package
  description: HR Apps Team Catalog
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-test/jbelamaric-demo-team-catalog-hr-apps
    secretRef:
      name: nephio-test-auth
  type: git
