apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/deployment-environment: production
    nephio.org/region: us-central1
    nephio.org/site-type: edge
    nephio.org/site: us-central1-edge-04
  name: us-central1-edge-04
  namespace: default
spec:
  content: Package
  deployment: true
  description: US Central 1 Edge Site 04 Cluster Workloads
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-test/jbelamaric-demo-us-central1-edge-04.git
    secretRef:
      name: nephio-test-auth
  type: git
