apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/deployment-environment: production
    nephio.org/region: us-central2
    nephio.org/site-type: regional
    nephio.org/site: us-central2-regional
  name: us-central2-regional
  namespace: default
spec:
  content: Package
  deployment: true
  description: US Central 2 Regional Cluster Workloads
  git:
    branch: main
    createBranch: true
    directory: /us-central2-regional
    repo: https://github.com/johnbelamaric/nephio-testorg-deploy.git
    secretRef:
      name: nephio-testorg-packages-auth
  type: git
