apiVersion: config.porch.kpt.dev/v1alpha1
kind: Repository
metadata:
  labels:
    kpt.dev/deployment-environment: production
    nephio.org/region: us-east1
    nephio.org/site-type: regional
    nephio.org/site: us-east1-regional-01
  name: us-east1-regional-01
  namespace: default
spec:
  content: Package
  deployment: true
  description: US East 1 Regional 01 Cluster Workloads
  git:
    branch: main
    createBranch: true
    directory: /
    repo: https://github.com/nephio-test/jbelamaric-us-east1-regional-01.git
    secretRef:
      name: nephio-test-auth
  type: git
